---
- name: Add apt key
  apt_key:
    # If you need to change the key use at least gpg --keyid-format long keyfile
    # the 32-bit short format is easily collided and insecure.
    url=http://ossec.wazuh.com/repos/apt/conf/ossec-key.gpg.key
    id=14B9C8DB9A1B1C65

- name: Add apt repository
  apt_repository:
    repo='deb http://ossec.wazuh.com/repos/apt/ubuntu/ {{ansible_distribution_release}} main'
    state=present

- name: Install
  apt:
    name=ossec-hids-agent

- name: Add configuration
  template:
    src=ossec.conf
    dest=/var/ossec/etc/ossec.conf
    owner=root
    group=ossec
  notify: restart ossec

- name: Register agent
  command: /var/ossec/bin/agent-auth -m {{ossec_server}}
  args:
    creates: /var/ossec/etc/client.keys

- name: Copy init.d for ossec
  copy:
    src=ossec
    dest=/etc/init.d
    mode=0755
